Projekt został zaczerpnięty ze strony kaggle.com . Generalnie również używa technik deep learning i do rozpoznawania obrazów używa tensorflow. Dokładność(accurancy) modelu jest nie mniejsza niż 90%. Komentarzy tym razem jest mniej bo by się powtarzały z wcześniejszych projektów.
https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import kagglehub
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization, ReLU
from tensorflow.keras.models import Sequential

In [2]:
# Download latest version
path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'chest-xray-pneumonia' dataset.
Path to dataset files: /kaggle/input/chest-xray-pneumonia

In [3]:
train_path = f'{path}/chest_xray/train'
test_path = f'{path}/chest_xray/test'
val_path = f'{path}/chest_xray/val'
"""
train_ds = train_gen.flow_from_directory(f'{path}/chest_xray/train', target_size=(224,224),
                                         batch_size=32, class_mode='binary')
test_ds = train_gen.flow_from_directory(f'{path}/chest_xray/test', target_size=(224,224),
                                         batch_size=32, class_mode='binary')

val_ds = val_gen.flow_from_directory(f'{path}/chest_xray/val', target_size=(224,224),
                                     batch_size=32, class_mode='binary')
"""

"\ntrain_ds = train_gen.flow_from_directory(f'{path}/chest_xray/train', target_size=(224,224),\n                                         batch_size=32, class_mode='binary')\ntest_ds = train_gen.flow_from_directory(f'{path}/chest_xray/test', target_size=(224,224),\n                                         batch_size=32, class_mode='binary')\n\nval_ds = val_gen.flow_from_directory(f'{path}/chest_xray/val', target_size=(224,224),\n                                     batch_size=32, class_mode='binary')\n"

In [5]:
#print(dir(train_ds))

In [7]:
#train_ds

In [9]:
#print(train_ds.class_indices)

In [10]:
filepaths =[]
labels = []

folds = os.listdir(train_path)
for fold in folds:
    f_path = os.path.join(train_path , fold)
    filelists = os.listdir(f_path)
    for file in filelists:
        filepaths.append(os.path.join(f_path , file))
        labels.append(fold)

In [11]:
filepaths

['/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1180_virus_2010.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1230_virus_2081.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1513_virus_2632.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person124_virus_238.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person746_virus_1369.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person588_bacteria_2422.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person466_virus_960.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1590_bacteria_4175.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person399_bacteria_1805.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person59_bacteria_279.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person57_bacteria_270.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person600_bacteria_2456.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1527_virus_2661.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1418_bacteria_3636.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person622_bacteria_2494.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1361_bacteria_3476.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person494_virus_1000.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person97_virus_180.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1689_bacteria_4472.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person437_bacteria_1884.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person74_bacteria_361.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1338_bacteria_3397.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person114_virus_217.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person300_bacteria_1421.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1197_virus_2039.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1585_bacteria_4151.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person412_bacteria_1827.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person318_bacteria_1474.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1519_virus_2646.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person332_virus_685.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person579_bacteria_2381.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person888_virus_1538.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1906_bacteria_4803.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person266_bacteria_1245.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1490_virus_2596.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person571_virus_1114.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1010_bacteria_2941.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person535_bacteria_2255.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person321_bacteria_1487.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person775_virus_1404.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1585_bacteria_4155.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1502_bacteria_3928.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person300_bacteria_1422.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1851_bacteria_4722.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person54_bacteria_257.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1289_bacteria_3252.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1409_virus_2413.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1453_virus_2485.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person349_bacteria_1605.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1303_virus_2243.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person267_bacteria_1252.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1595_bacteria_4183.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1346_bacteria_3430.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person66_bacteria_325.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person590_virus_1138.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person53_bacteria_253.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person961_bacteria_2886.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person343_bacteria_1584.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1340_virus_2312.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1099_virus_1819.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1465_virus_2530.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person935_virus_1597.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1411_bacteria_3610.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person148_virus_298.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person657_virus_1240.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person723_virus_1342.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person536_virus_1064.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person438_virus_889.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1507_bacteria_3944.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1123_virus_1848.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1073_virus_1776.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1414_bacteria_3628.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person25_bacteria_115.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1177_virus_2000.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1323_bacteria_3363.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person833_virus_1469.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person959_bacteria_2884.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1343_bacteria_3419.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1259_virus_2139.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1489_virus_2594.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person41_bacteria_209.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person743_bacteria_2646.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person448_bacteria_1935.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person909_virus_1565.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1343_virus_2316.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person99_virus_183.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person354_bacteria_1634.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person160_virus_316.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1265_virus_2156.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person567_virus_1107.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person728_bacteria_2630.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person360_bacteria_1647.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person337_bacteria_1557.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person475_bacteria_2022.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1663_bacteria_4412.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person419_virus_859.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1065_bacteria_2999.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person26_bacteria_124.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person257_virus_538.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1481_bacteria_3868.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person567_bacteria_2353.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person389_bacteria_1780.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person62_bacteria_301.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person629_bacteria_2506.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person431_bacteria_1872.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1494_virus_2601.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person312_virus_635.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1016_virus_1704.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person336_bacteria_1552.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1701_bacteria_4504.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1381_bacteria_3516.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1368_virus_2354.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person407_virus_812.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1490_bacteria_3891.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1810_bacteria_4664.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1267_virus_2160.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1059_bacteria_2993.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1491_virus_2597.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person700_bacteria_2599.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person531_bacteria_2241.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1674_bacteria_4437.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1731_bacteria_4563.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1315_bacteria_3322.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1907_bacteria_4806.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person314_bacteria_1462.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person135_virus_270.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person156_virus_308.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1188_virus_2024.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1460_bacteria_3801.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person326_bacteria_1503.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person395_bacteria_1794.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1372_bacteria_3503.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person753_bacteria_2656.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person369_bacteria_1680.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1509_virus_2621.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person26_bacteria_127.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1084_bacteria_3024.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person420_bacteria_1847.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person567_bacteria_2354.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1155_virus_1934.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1024_bacteria_2955.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person24_bacteria_109.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person440_virus_893.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person441_bacteria_1904.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person298_virus_617.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person925_bacteria_2850.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person911_virus_1567.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1200_virus_2042.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1158_virus_1940.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person476_bacteria_2026.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person449_bacteria_1940.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person423_bacteria_1855.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person259_bacteria_1217.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person393_virus_784.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1521_virus_2649.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person703_bacteria_2602.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person963_virus_1636.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person528_virus_1049.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person563_bacteria_2338.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person608_bacteria_2472.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person937_virus_1599.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person7_bacteria_29.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person510_virus_1026.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person764_bacteria_2668.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person437_bacteria_1888.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1139_bacteria_3082.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person477_bacteria_2030.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person74_bacteria_362.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1297_bacteria_3260.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person277_bacteria_1306.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person61_bacteria_292.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person426_bacteria_1861.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person56_bacteria_268.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person23_bacteria_99.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person24_bacteria_110.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person581_virus_1125.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1848_bacteria_4719.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1715_bacteria_4532.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person145_virus_295.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1576_bacteria_4127.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1366_bacteria_3490.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person22_bacteria_74.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person744_virus_1367.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person61_bacteria_288.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person359_virus_738.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person274_bacteria_1290.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1449_bacteria_3743.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person277_virus_571.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person41_bacteria_206.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1344_virus_2320.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person739_bacteria_2642.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person94_virus_176.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person987_bacteria_2914.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person108_virus_199.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person630_bacteria_2515.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1286_bacteria_3249.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person972_virus_1646.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person426_bacteria_1863.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person585_bacteria_2412.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1040_bacteria_2974.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person354_bacteria_1635.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person783_virus_1414.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person441_bacteria_1914.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person698_virus_1294.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person989_virus_1667.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person413_bacteria_1830.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person875_bacteria_2798.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person1214_bacteria_3166.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person351_bacteria_1619.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person596_virus_1149.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person445_virus_918.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person896_bacteria_2821.jpeg',
 '/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person895_bacteria_2820.jpeg',

In [12]:
labels

['PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 'PNEUMONIA',
 ...]

In [13]:
filepaths_train = pd.Series(filepaths , name = 'filepaths')
labels_train = pd.Series(labels , name = 'label')

In [14]:
filepaths_train

0       /kaggle/input/chest-xray-pneumonia/chest_xray/...
1       /kaggle/input/chest-xray-pneumonia/chest_xray/...
2       /kaggle/input/chest-xray-pneumonia/chest_xray/...
3       /kaggle/input/chest-xray-pneumonia/chest_xray/...
4       /kaggle/input/chest-xray-pneumonia/chest_xray/...
                              ...
5211    /kaggle/input/chest-xray-pneumonia/chest_xray/...
5212    /kaggle/input/chest-xray-pneumonia/chest_xray/...
5213    /kaggle/input/chest-xray-pneumonia/chest_xray/...
5214    /kaggle/input/chest-xray-pneumonia/chest_xray/...
5215    /kaggle/input/chest-xray-pneumonia/chest_xray/...
Name: filepaths, Length: 5216, dtype: object

In [15]:
labels_train

0       PNEUMONIA
1       PNEUMONIA
2       PNEUMONIA
3       PNEUMONIA
4       PNEUMONIA
          ...
5211       NORMAL
5212       NORMAL
5213       NORMAL
5214       NORMAL
5215       NORMAL
Name: label, Length: 5216, dtype: object

In [16]:
filepaths =[]
labels = []

folds = os.listdir(test_path)
for fold in folds:
    f_path = os.path.join(test_path , fold)
    filelists = os.listdir(f_path)
    for file in filelists:
        filepaths.append(os.path.join(f_path , file))
        labels.append(fold)

In [17]:
filepaths_test = pd.Series(filepaths , name = 'filepaths')
labels_test = pd.Series(labels , name = 'label')

In [18]:
filepaths_test

0      /kaggle/input/chest-xray-pneumonia/chest_xray/...
1      /kaggle/input/chest-xray-pneumonia/chest_xray/...
2      /kaggle/input/chest-xray-pneumonia/chest_xray/...
3      /kaggle/input/chest-xray-pneumonia/chest_xray/...
4      /kaggle/input/chest-xray-pneumonia/chest_xray/...
                             ...
619    /kaggle/input/chest-xray-pneumonia/chest_xray/...
620    /kaggle/input/chest-xray-pneumonia/chest_xray/...
621    /kaggle/input/chest-xray-pneumonia/chest_xray/...
622    /kaggle/input/chest-xray-pneumonia/chest_xray/...
623    /kaggle/input/chest-xray-pneumonia/chest_xray/...
Name: filepaths, Length: 624, dtype: object

In [19]:
labels_test

0      PNEUMONIA
1      PNEUMONIA
2      PNEUMONIA
3      PNEUMONIA
4      PNEUMONIA
         ...
619       NORMAL
620       NORMAL
621       NORMAL
622       NORMAL
623       NORMAL
Name: label, Length: 624, dtype: object

In [20]:
#labels_train = np.array(labels_train).reshape(-1, 1)

In [21]:
"""
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
labels_train_encoded = encoder.fit_transform(labels_train)
labels_train_encoded
"""

"\nencoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)\nlabels_train_encoded = encoder.fit_transform(labels_train)\nlabels_train_encoded\n"

In [22]:
"""
le = LabelEncoder()
labels_train_encoded = le.fit_transform(labels_train)
"""

'\nle = LabelEncoder()\nlabels_train_encoded = le.fit_transform(labels_train)\n'

In [23]:
X_train, X_test, y_train, y_test = \
    train_test_split(filepaths_train, labels_train, test_size=0.2, random_state=42, stratify=labels_train)

In [24]:
train_df = pd.DataFrame({'filename': X_train, 'label': y_train})
val_df = pd.DataFrame({'filename': X_test, 'label': y_test})

In [25]:
train_df

                                               filename      label
3974  /kaggle/input/chest-xray-pneumonia/chest_xray/...     NORMAL
5159  /kaggle/input/chest-xray-pneumonia/chest_xray/...     NORMAL
3801  /kaggle/input/chest-xray-pneumonia/chest_xray/...  PNEUMONIA
24    /kaggle/input/chest-xray-pneumonia/chest_xray/...  PNEUMONIA
1308  /kaggle/input/chest-xray-pneumonia/chest_xray/...  PNEUMONIA
...                                                 ...        ...
3140  /kaggle/input/chest-xray-pneumonia/chest_xray/...  PNEUMONIA
1063  /kaggle/input/chest-xray-pneumonia/chest_xray/...  PNEUMONIA
4580  /kaggle/input/chest-xray-pneumonia/chest_xray/...     NORMAL
2391  /kaggle/input/chest-xray-pneumonia/chest_xray/...  PNEUMONIA
1705  /kaggle/input/chest-xray-pneumonia/chest_xray/...  PNEUMONIA

[4172 rows x 2 columns]

In [26]:
# Dla treningu – z augmentacją
train_datagen = ImageDataGenerator(rescale=1./255,
                                   rotation_range=10,
                                   zoom_range=0.1,
                                   horizontal_flip=True)

# Dla walidacji – bez augmentacji
val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='filename',
    y_col='label',
    target_size=(224, 224),
    class_mode='binary',
    batch_size=32,
    shuffle=True
)

val_generator = val_datagen.flow_from_dataframe(
    dataframe=val_df,
    x_col='filename',
    y_col='label',
    target_size=(224, 224),
    class_mode='binary',
    batch_size=32,
    shuffle=False
)

Found 4172 validated image filenames belonging to 2 classes.
Found 1044 validated image filenames belonging to 2 classes.

In [27]:
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)), # Changed input shape to 3 channels
    BatchNormalization(),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Dropout(0.25),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Dropout(0.25),
    Flatten(),

    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid') # Output layer for binary classification
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
# Kompilacja
model.compile(optimizer='adam',
              loss='binary_crossentropy', # Loss function for binary classification
              metrics=['accuracy'])

In [29]:

history = model.fit(train_generator,
                    validation_data=val_generator,
                    epochs=10,
                    verbose=1)

Epoch 1/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 1957s 15s/step - accuracy: 0.8094 - loss: 1.4067 - val_accuracy: 0.8305 - val_loss: 0.5038
Epoch 2/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 1968s 15s/step - accuracy: 0.8991 - loss: 0.2644 - val_accuracy: 0.8870 - val_loss: 0.2989
Epoch 3/10
  1/131 ━━━━━━━━━━━━━━━━━━━━ 32:15 15s/step - accuracy: 0.9688 - loss: 0.1095

KeyboardInterrupt: