**Wszystkie komentarze znajdują się w kodzie strony.**

In [ ]:
# ładowanie modułów i funkcji
from pathlib import Path
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import numpy as np
from sklearn.model_selection import train_test_split
import keras

In [ ]:
# ładowanie danych iris
def load_iris_data():
      filename = "iris.csv"
      Path("data/irisData").mkdir(parents=True, exist_ok=True)
      return pd.read_csv(Path("data/irisData") / filename, sep=',')

iris = load_iris_data()

In [ ]:
# kilka metod służących podglądowi danych
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
iris.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
iris["variety"].value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [ ]:
# podział danych na true labels i reszte służacych trenowaniu sieci neuronowych
cols = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width']
X = iris[cols]
y = iris['variety']

In [ ]:
# zmieniamy dane kategoryczne w true labels na wartości zero-jedynkowe
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
y_encoded = encoder.fit_transform(y.values.reshape(-1, 1))

In [ ]:
# skalowanie
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
# podział danych na treningowe i testowe
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

In [ ]:
# model sieci neuronowych
class MyModel(keras.Model):
    def __init__(self):
        super().__init__()
        self.dense1 = keras.layers.Dense(32, activation="relu")
        self.dense2 = keras.layers.Dense(3, activation="softmax")

    def call(self, inputs):
        x = self.dense1(inputs)
        return self.dense2(x)

model = MyModel()
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [ ]:
# trenowanie modelu
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 116ms/step - accuracy: 0.7408 - loss: 0.8941 - val_accuracy: 0.7333 - val_loss: 0.8694
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8010 - loss: 0.8634 - val_accuracy: 0.8333 - val_loss: 0.8296
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7900 - loss: 0.8312 - val_accuracy: 0.8333 - val_loss: 0.7920
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.8269 - loss: 0.7791 - val_accuracy: 0.9000 - val_loss: 0.7565
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8406 - loss: 0.7491 - val_accuracy: 0.9333 - val_loss: 0.7232
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8483 - loss: 0.7299 - val_accuracy: 0.9333 - val_loss: 0.6917
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8792 - loss: 0.6970 - val_accuracy: 0.9333 - val_loss: 0.6622
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8852 - loss: 0.6647 - val_accuracy: 0.9000 - val_loss: 0.6340
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8863 - loss: 0.6253 - val_accuracy: 0.9000 - val_loss: 0.6080
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8567 - loss: 0.6132 - val_accuracy: 0.9000 - val_loss: 0.5839